/// A broadcast safety alert (weather/crime/traffic/disaster), generated by
/// authorities or the AI/CV pipeline and written to
/// `AppConstants.colSafetyAlerts`. Read-only from the mobile app - see
/// `firestore.rules`' `safety_alerts/{alertId}` block (`allow write: if
/// isAuthority()`).
class SafetyAlertEntity {
  final String id;
  final String title;
  final String body;
  final String type; // 'flood' | 'crime' | 'traffic' | 'weather' | 'general'
  final String severity; // 'low' | 'medium' | 'high' | 'critical'
  final DateTime createdAt;

  SafetyAlertEntity({
    required this.id,
    required this.title,
    required this.body,
    required this.type,
    required this.severity,
    required this.createdAt,
  });
}
