/// A safety-score snapshot for a city zone, generated by the AI prediction
/// engine (`ai_engine`). Reads only - this pass doesn't write these; they're
/// populated by the AI/CV heatmap pipeline once it lands.
class AreaSafetyEntity {
  final String id;
  final String zoneName;
  final double safetyScore; // 0-100, see AppConstants.safetyScore* thresholds
  final String summary;
  final double latitude;
  final double longitude;
  final DateTime updatedAt;

  AreaSafetyEntity({
    required this.id,
    required this.zoneName,
    required this.safetyScore,
    required this.summary,
    required this.latitude,
    required this.longitude,
    required this.updatedAt,
  });
}
